### ISSUE TITLE
Error Creating new torrent

### ISSUE THREAD

**Issue by soulspark666** [rndusr/torf-cli#17]
Using the following command 

```
torf 'sample' \
-t http://nyaa.tracker.wf:7777/announce \
-t http://open.nyaatorrents.info:6544/announce \
-t http://anidex.moe:6969/announce	\
-t http://tracker.anirena.com:80/announce \
-t udp://open.stealth.si:80/announce \
-t udp://tracker.opentrackr.org:1337/announce \
-t udp://tracker.uw0.xyz:6969 \
-t udp://tracker.coppersurfer.tk:6969/announce \
-t udp://tracker.openbittorrent.com:80/announce \
-P -o sample.torrent
```

shows the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/torf", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/torfcli/__init__.py", line 21, in run
    run()
  File "/usr/local/lib/python3.6/dist-packages/torfcli/_main.py", line 43, in run
    _create_mode(cfg)
  File "/usr/local/lib/python3.6/dist-packages/torfcli/_main.py", line 71, in _create_mode
    created_by=None if cfg['nocreator'] else _config.DEFAULT_CREATOR
TypeError: __init__() got an unexpected keyword argument 'exclude'
```

**Comment by rndusr** [comment]
Looks you somehow updated torf but not torf-cli?

Try installing the latest torf-cli version.

Post the output of `pip3 show torf torf-cli` if that doesn't work.

**Comment by soulspark666** [comment]
Sorry, I forgot to write the steps to reproduce the error:
```
pip3 install torf-cli
```
this shows the following:
```
Collecting torf-cli
  Downloading https://files.pythonhosted.org/packages/fd/31/c7202688308fd4028f16cac6f590d316c481f91391c7e04242f66ed29fd9/torf_cli-3.0.1-py3-none-any.whl
Collecting torf>=2.0.0
  Downloading https://files.pythonhosted.org/packages/78/8c/4b5b6244b9517e0435f8d1a4aa8659f5de3af14f6ad5188041a91be599fe/torf-3.0.0-py3-none-any.whl (92kB)
     |████████████████████████████████| 102kB 5.4MB/s 
Collecting pyxdg
  Downloading https://files.pythonhosted.org/packages/39/03/12eb9062f43adb94e30f366743cb5c83fd15fef026500cd4de42c7c12280/pyxdg-0.26-py2.py3-none-any.whl (40kB)
     |████████████████████████████████| 40kB 6.7MB/s 
Collecting flatbencode==0.2.*
  Downloading https://files.pythonhosted.org/packages/96/3d/ed36c2a94bef2ff1b7fc62ba932fa2eb4db3f7ea30c89da01b1c64ecbb8c/flatbencode-0.2.1.tar.gz
Building wheels for collected packages: flatbencode
  Building wheel for flatbencode (setup.py) ... done
  Created wheel for flatbencode: filename=flatbencode-0.2.1-cp36-none-any.whl size=3281 sha256=28e6a936bc2e53055059f693a28ec6c91643c6f1b161263edff050b09a8e3b8c
  Stored in directory: /root/.cache/pip/wheels/29/58/c2/0aca5bf762211cfb8f03506a3fe3022b3d460c224d21cc4034
Successfully built flatbencode
Installing collected packages: flatbencode, torf, pyxdg, torf-cli
Successfully installed flatbencode-0.2.1 pyxdg-0.26 torf-3.0.0 torf-cli-3.0.1
```

**Comment by soulspark666** [comment]
and 
```
pip3 show torf torf-cli
```
shows the following
```
Name: torf
Version: 3.0.0
Summary: Python 3 module for creating and parsing torrent files and magnet URIs
Home-page: https://github.com/rndusr/torf
Author: Random User
Author-email: rndusr@posteo.de
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: flatbencode
Required-by: torf-cli
---
Name: torf-cli
Version: 3.0.1
Summary: CLI tool to create, read and edit torrent files
Home-page: https://github.com/rndusr/torf-cli
Author: Random User
Author-email: rndusr@posteo.de
License: GPLv3+
Location: /usr/local/lib/python3.6/dist-packages
Requires: torf, pyxdg
Required-by: 
```

**Comment by rndusr** [comment]
I actually forgot to bump the mininum torf version in torf-cli, but that doesn't
seem to be the issue in your case since it uses torf 3.0.0 anyway.

Is it possible you have torf installed in your home directory?
Does `ls .local/lib/*/site-packages/torf/` show anything?

**Comment by soulspark666** [comment]
``ls .local/lib/*/site-packages/torf/``
shows
```ls: cannot access '.local/lib/*/site-packages/torf/': No such file or directory```

**Comment by rndusr** [comment]
Try this: `python3 -c 'import torf; print(torf)'`

It should print something like:

    <module 'torf' from '/path/to/torf/torf/__init__.py'>

Then check the version with the copied path to __init__.py:
`grep __version__ /path/to/torf/torf/__init__.py`

**Comment by soulspark666** [comment]
Here is the output
![ss](https://user-images.githubusercontent.com/37495396/78351429-4a480700-7596-11ea-85bb-66ae77906bf1.png)

**Comment by rndusr** [comment]
If you re-install or upgrade torf-cli, everything should work now.

I never really released the new torf-cli version. There was a minor
misconfiguration and PyPI refused the release, but I missed the error message.

The old version of torf-cli had "torf>=2" as a requirement, so it used the new
3.0.0 release even though it wasn't compatible. This shouldn't happen in the
future. torf-cli now depends on "torf==3".

The lesson: Do not trust your scripts. They are idiots.

**Comment by soulspark666** [comment]
So I tried with aa fresh install:
``pip3 install torf-cli``
```
Collecting torf-cli
  Downloading https://files.pythonhosted.org/packages/7c/b0/68aa3956c90a9000dff99d7ab103e426d2bee4d1ee8ff4ce202a85443037/torf_cli-3.1.0-py3-none-any.whl
Collecting torf==3
  Downloading https://files.pythonhosted.org/packages/78/8c/4b5b6244b9517e0435f8d1a4aa8659f5de3af14f6ad5188041a91be599fe/torf-3.0.0-py3-none-any.whl (92kB)
     |████████████████████████████████| 102kB 5.3MB/s 
Collecting pyxdg
  Downloading https://files.pythonhosted.org/packages/39/03/12eb9062f43adb94e30f366743cb5c83fd15fef026500cd4de42c7c12280/pyxdg-0.26-py2.py3-none-any.whl (40kB)
     |████████████████████████████████| 40kB 4.4MB/s 
Collecting flatbencode==0.2.*
  Downloading https://files.pythonhosted.org/packages/96/3d/ed36c2a94bef2ff1b7fc62ba932fa2eb4db3f7ea30c89da01b1c64ecbb8c/flatbencode-0.2.1.tar.gz
Building wheels for collected packages: flatbencode
  Building wheel for flatbencode (setup.py) ... done
  Created wheel for flatbencode: filename=flatbencode-0.2.1-cp36-none-any.whl size=3281 sha256=58d60b3b7ce6d99afe0d13a4d937b5e6d417484632f59ee621ade4c9e0580f13
  Stored in directory: /root/.cache/pip/wheels/29/58/c2/0aca5bf762211cfb8f03506a3fe3022b3d460c224d21cc4034
Successfully built flatbencode
Installing collected packages: flatbencode, torf, pyxdg, torf-cli
Successfully installed flatbencode-0.2.1 pyxdg-0.26 torf-3.0.0 torf-cli-3.1.0
```
and while I tried to run the same command as in the begining

```
Traceback (most recent call last):
  File "/usr/local/bin/torf", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/torfcli/__init__.py", line 31, in run
    torrent = _main.run(ui)
  File "/usr/local/lib/python3.6/dist-packages/torfcli/_main.py", line 35, in run
    return _create_mode(ui, cfg)
  File "/usr/local/lib/python3.6/dist-packages/torfcli/_main.py", line 72, in _create_mode
    created_by=None if cfg['nocreator'] else _config.DEFAULT_CREATOR
  File "/usr/local/lib/python3.6/dist-packages/torf/_torrent.py", line 120, in __init__
    self.path = path
  File "/usr/local/lib/python3.6/dist-packages/torf/_torrent.py", line 172, in path
    self._set_files(filepaths, basepath)
  File "/usr/local/lib/python3.6/dist-packages/torf/_torrent.py", line 324, in _set_files
    elif len(files) == 1 and files[0] == basepath:
  File "/usr/local/lib/python3.6/dist-packages/torf/_utils.py", line 319, in __eq__
    return self._path == other._path and self._size == other._size
AttributeError: 'PosixPath' object has no attribute '_path'
```

**Comment by soulspark666** [comment]
@rndusr , please let me know how to fix it, as it is not working even now!

**Comment by rndusr** [comment]
Sorry, I should've replied.

I'm working on it. I'll try and make a bugfix release today.

The issue is Python 3.6 (or rather my lack of testing against it). You could fix
this immediately by installing Python 3.7 or later, but I guess that's not an
option.

**Comment by rndusr** [comment]
I just made a new release (3.1.1) that should fix this.

**Comment by soulspark666** [comment]
Will test it out and report the results.

**Comment by soulspark666** [comment]
@rndusr the recent fix, fixed the issue and it started working again.

**Comment by rndusr** [comment]
Great, thanks for reporting back.
